# Build script used by gitlab.medelexis.ch
variables:
   ORIGIN_BRANCH: master

stages:
    - build
    - trigger_other_builds

build:
  stage: build
  script:
  - if [ $(curl -s --head -w %{http_code} http://download.elexis.info/elexis/$CI_COMMIT_REF_NAME/p2/target/ -o /dev/null) == '200' ]; then export BUILD_TARGET_BRANCH=$CI_COMMIT_REF_NAME; fi
  - if [ $(curl -s --head -w %{http_code} http://download.elexis.info/elexis/$CI_COMMIT_REF_NAME/p2/elexis-3-core/ -o /dev/null) == '200' ]; then export BUILD_CORE_BRANCH=$CI_COMMIT_REF_NAME; fi
  - xvfb-run mvn clean verify ${BUILD_TARGET_BRANCH:+-Dgit.target.branch=$BUILD_TARGET_BRANCH} ${BUILD_CORE_BRANCH:+-Dgit.core.branch=$BUILD_CORE_BRANCH} -Dtycho.localArtifacts=ignore -Pall-archs
  - jo token="$WEBHOOK_TOKEN" info="elexis-3-gpl $CI_JOB_ID $ORIGIN_BRANCH $CI_COMMIT_REF_NAME $CI_COMMIT_SHA" binary=%$(find ch.elexis.gpl.p2site/target/ch.elexis.gpl.p2site*.zip) destDir=elexis/$CI_COMMIT_REF_NAME/p2/elexis-3-gpl | curl -k -H "Content-Type:application/json" -X POST -d @- $WEBHOOK_URL/deploy-zip
  only:
  - master@elexis/elexis-3-gpl
  - /^\d*[.]\d*$/@elexis/elexis-3-gpl
  - /^[bf]\d*$/@elexis/elexis-3-gpl
