# Build script used by gitlab.medelexis.ch
variables:
   ORIGIN_BRANCH: "3.7"

stages:
    - build
    - trigger_other_builds

build:
  stage: build
  script:
  - if [ $(curl -s --head -w %{http_code} http://download.elexis.info/elexis/$CI_COMMIT_REF_NAME/p2/target/ -o /dev/null) == '200' ]; then export BUILD_TARGET_BRANCH=$CI_COMMIT_REF_NAME; fi 
  - if [ $(curl -s --head -w %{http_code} http://download.elexis.info/elexis/$CI_COMMIT_REF_NAME/p2/elexis-3-core/ -o /dev/null) == '200' ]; then export BUILD_CORE_BRANCH=$CI_COMMIT_REF_NAME; fi 
  - xvfb-run mvn clean verify ${BUILD_TARGET_BRANCH:+-Dgit.target.branch=$BUILD_TARGET_BRANCH} ${BUILD_CORE_BRANCH:+-Dgit.core.branch=$BUILD_CORE_BRANCH} -Dtycho.localArtifacts=ignore -Pall-archs
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$SSH_PRIVATE_KEY_ED25519_BASE64" | base64 -d)
  - rsync -aiv --delete --mkpath -e ssh ch.elexis.gpl.p2site/target/repository/ deploy@download.medelexis.ch:download.elexis.info/elexis/$CI_COMMIT_REF_NAME/p2/elexis.3.gpl/
  - eval $(ssh-agent -k)
  only:
  - 3.7@elexis/elexis-3-gpl
  - /^\d*[.]\d*$/@elexis/elexis-3-gpl
  - /^[bf]\d*$/@elexis/elexis-3-gpl
