---
language: java

install: mvn  -V -DskipTests=true -Dmaven.javadoc.skip=true -B validate

script: mvn  -V --quiet clean verify -Dtycho.localArtifacts=ignore && find . -name "*.zip"
  
notifications:
  email:
  - niklaus.giger@member.fsf.org
jdk:
  - oraclejdk8

cache:
  directories:
  - $HOME/.m2
